debug: false # (Optional) Enable debug mode. This will log more information to the console.

# (Optional) This will send Amethyst related errors to the discord webhook.
send-errors-to-discord: false
discord-webhook: ""

logged-packages:
  - wtf.casper

paste-services: # (Optional) Paste services to use when uploading debug logs. True is enabled and false is disabled.
  pastebin: false
  hastebin: false
  mclogs: true
  pastesdev: false

pastebin:
  api-key: ""
  user-key: "" # ends up as a fallback I think